### ISSUE TITLE
conan install issue

### ISSUE THREAD

**Issue by DrFishWave** [Prograda/Skybolt#43] opened 2024-08-21 07:29 UTC
After running "conan install %SKYBOLT_SOURCE% --install-folder=%SKYBOLT_BUILD% -o openscenegraph-mr:shared=True -o enable_python=True -o enable_qt=True -o enable_bullet=True -o enable_cigi=True", 
the error message "ERROR: Conflict in qt/5.15.11:'qt/5.15.11' requires 'freetype/2.13.2' while 'openscenegraph-mr/3.7.0@user/stable' requires 'freetype/2.13.0'.To fix this conflict you need to override the package 'freetype' in your root package." appears.
How to solve this problem?

**Comment by matthew-reid** [comment] 2024-08-24 13:46
The problem is caused by `openscenegraph` and `qt` requiring different versions of `freetype` in your configuration. The skybolt v1.6.0 and v1.5.1 tags both specify package recipe revision hashes which should ensure there is no version mismatch. However unfortunately conan 1.x ignores the revision hashes by default and just tries to use the latest recipe revision, which might be causing the mismatch.

To fix this problem, you can try enabling recipe revisions in conan by setting  `CONAN_REVISIONS_ENABLED=1` in your environment. You can read more about it [here](https://docs.conan.io/1/versioning/revisions.html).

**Comment by matthew-reid** [comment] 2024-11-07 07:51
Issue should now be resolved by using conan 2 which is supported as of Skybolt 1.7.

**Closed by matthew-reid** 2024-11-07 07:51 UTC
