### ISSUE TITLE
Terrain doesn't load in FlightSimApp.

### ISSUE THREAD

**Issue by ozhanghe** [Prograda/Skybolt#38] opened 2024-03-22 00:02 UTC
`[2024-03-21 16:58:11.742853] [0x00005894] [error]   Error reading file https://api.mapbox.com/v4/mapbox.satellite/0/0/0.jpg?access_token=xxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxx: file not handled`
It gives this error when trying to load terrain, but when I open this url in the browser, it loads. It also works if I put a file path in the asset package. My OSGDB can't load internet images. 

Using: conan + cmake Windows 11

**Comment by matthew-reid** [comment] 2024-04-06 01:32
The problem was caused by the OSG curl plugin requiring SSL certificate by default. Fixed in 61dd843d5341f8e52a3470f97960134ee96cccfb

**Closed** 2024-05-04 08:38 UTC
